sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '6'
before_install:
  - npm install -g npm@~1.4.6
before_script:
  - npm prune
script:
  - npm run test
after_success:
branches:
  only:
    - master
